---
# Tools binaries installation recipe
# - liftover
# - bedGraphToBigWig

#______________________________________
# Install dependencies

# CentOS 7
- name: '[EL] Install binary depedencencies'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - libpng12
   - python-pysam
  when: ansible_os_family == "RedHat"

# Ubuntu
- name: '[Ubuntu] Install binary depedencencies'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libpng
    - python-pysam
  when: ansible_os_family == "Debian"

#______________________________________
# Install binaries

- name: Download binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dist }}"
    mode: "a+x"
  with_items:
    - { url: '{{ ucsc_download_url }}//liftOver', dest: '{{ bin_path}}' }
    - { url: '{{ ucsc_download_url }}/bedGraphToBigWig', dest: '{{ bin_path }}' }
