---
# tasks file for ansible-role-galaxycloud-tooldeps

- include: prerequisites.yml 
  when: node_type == 'front'

# Check if Galaxy is up
- include: check_galaxy.yml
  when: node_type == 'front'

# Get Conda prefix
- include: get_conda.yml
  when: node_type == 'front'

# Install tools dependencies
- include: dependencies.yml

# Install binaries (e.g. liftover)
- include: bin.yml
  when: install_bin|bool
